import type { Metadata } from 'next'
import SildebarForm from '@/compronent/Profile/SildebarForm'
import { getSession } from '@/utils/auth'
import NavBar from '@/compronent/nevigation/NavBar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getSession();
    return (
        <div className='bg-white w-full'>
            {children}
        </div>
    )
}
