import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomProvider } from "./provider";
import NavBar from "@/compronent/nevigation/NavBar";
import { getSession } from '@/utils/auth';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={` ${inter.className} flex justify-center w-full text-black bg-gray-100 bg-gradient-to-r overflow-y-scroll`}>
        <CustomProvider>
        {children}
        </CustomProvider>
      </body>
    </html>
  );
}
