import type { Metadata } from 'next'
import SildebarForm from '@/compronent/Profile/SildebarForm'
import { getSession } from '@/utils/auth'
import NavBar from '@/compronent/nevigation/NavBar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getSession();
    return (
        <div className="flex flex-col w-2/3 border ">
            <NavBar session={session} />
            <div className=' flex justify-center w-full mt-5 '>
                <SildebarForm session={session} />
                <div className='flex flex-col md:w-[900px] h-screen border  mt-10'>
                    {children}
                </div>
            </div>
        </div>
    )
}
